package svk.opg.editor.treeeditor;

import java.awt.BorderLayout;
import javax.swing.JLabel;

/**
 *
 * @author Lubomir Hlavko
 */
public class BonePropPanel extends javax.swing.JPanel {

    /**
     * Creates new form BonePropPanel
     */
    public BonePropPanel() {
        initComponents();
    }
    
    public void setValues(String label, float length, float angle) {
        labelTitle.setText(label);
        fieldLength.setText(Float.toString(length));
        fieldAngle.setText(Float.toString(angle));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLength = new javax.swing.JLabel();
        labelAngle = new javax.swing.JLabel();
        fieldLength = new javax.swing.JFormattedTextField();
        fieldAngle = new javax.swing.JFormattedTextField();
        labelTitle = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(70, 60));

        labelLength.setText("length");

        labelAngle.setText("angle");

        fieldLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLengthActionPerformed(evt);
            }
        });

        fieldAngle.setMinimumSize(new java.awt.Dimension(6, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAngle)
                            .addComponent(labelLength))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLength)
                    .addComponent(fieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAngle)
                    .addComponent(fieldAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLengthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField fieldAngle;
    private javax.swing.JFormattedTextField fieldLength;
    private javax.swing.JLabel labelAngle;
    private javax.swing.JLabel labelLength;
    private javax.swing.JLabel labelTitle;
    // End of variables declaration//GEN-END:variables
}
